[2024-07-22T01:42:09.780+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T01:42:09.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-07-22T01:42:06.338754+00:00 [queued]>
[2024-07-22T01:42:09.806+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-07-22T01:42:06.338754+00:00 [queued]>
[2024-07-22T01:42:09.806+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T01:42:09.840+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_task> on 2024-07-22 01:42:06.338754+00:00
[2024-07-22T01:42:09.845+0000] {standard_task_runner.py:63} INFO - Started process 29312 to run task
[2024-07-22T01:42:09.847+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2024-07-22T01:42:06.338754+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpgg6wwfph']
[2024-07-22T01:42:09.848+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_task
[2024-07-22T01:42:09.897+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_dag.extract_task manual__2024-07-22T01:42:06.338754+00:00 [running]> on host codespaces-8c1ce7
[2024-07-22T01:42:10.001+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T01:42:06.338754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T01:42:06.338754+00:00'
[2024-07-22T01:42:10.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T01:42:10.003+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-22T01:42:10.003+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/top-level-domain-names.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestraded/manual-extract.csv']
[2024-07-22T01:42:10.012+0000] {subprocess.py:86} INFO - Output:
[2024-07-22T01:42:10.016+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestraded/manual-extract.csv: No such file or directory
[2024-07-22T01:42:10.017+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-22T01:42:10.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T01:42:10.023+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-22T01:42:10.026+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, run_id=manual__2024-07-22T01:42:06.338754+00:00, execution_date=20240722T014206, start_date=20240722T014209, end_date=20240722T014210
[2024-07-22T01:42:10.059+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 29312)
[2024-07-22T01:42:10.100+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T01:42:10.110+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T01:42:10.110+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
